### ISSUE TITLE
Wind Noise Reduction

### ISSUE THREAD

**Issue by kholgate** [semvis123/Sonyfy#8]
Noise cancelling and ambient mode set to '1' correctly changes between ANC and wind noise redcuction, however, it when closing and reopening the audio controls, it will always ship the state of 'Noise Cancelling' even if set to ambient. Off works correctly. The mode of the earphones stays correct (wf1000xm3) though it seems Sonyfy detects ambient lvl 1 / wind noise reduction as full ANC.

**Comment by semvis123** [comment]
That's right, it's expected behavior, because wind reduction is noise cancelling (even according to the internal representation of the app). I don't see why anyone would put wind reduction under ambient sound. I could make an exception for wind reduction, but I don't know if that's needed.

**Comment by semvis123** [comment]
I will close this issue due to inactivity, please reopen if needed.

**Comment by kholgate** [comment]
Sorry didn’t even see this. All good mate.


________________________________
